### ISSUE TITLE
Hidden properties not working in creation dialog

### ISSUE THREAD

**Issue by jonnitto** [bwaidelich/Wwwision.Neos.CreationDialogProperties#4]
If I expand a hidden property (starting with an `_`), it will shop up in the dialog, but the value will not be applied to the property

```yaml
'Some.Package:Some.NodeType':
  properties:
    _hiddenBeforeDateTime:
        options:
            showInCreationDialog: true
```
